### ISSUE TITLE
Could not use credentials

### ISSUE THREAD

**Issue by JSteunouSteeple** [event-catalog/generator-eventbridge#13]
### I tried this:

I tried to use this plugin (kudos :pray: ), create an IAM user using AWS predefined `AmazonEventBridgeSchemasReadOnlyAccess` rules.

```json
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "AmazonEventBridgeSchemasReadOnlyAccess",
            "Effect": "Allow",
            "Action": [
                "schemas:ListDiscoverers",
                "schemas:DescribeDiscoverer",
                "schemas:ListRegistries",
                "schemas:DescribeRegistry",
                "schemas:SearchSchemas",
                "schemas:ListSchemas",
                "schemas:ListSchemaVersions",
                "schemas:DescribeSchema",
                "schemas:GetDiscoveredSchema",
                "schemas:DescribeCodeBinding",
                "schemas:GetCodeBindingSource",
                "schemas:ListTagsForResource",
                "schemas:GetResourcePolicy"
            ],
            "Resource": "*"
        }
    ]
}
```

generate keys for it, use it in `credentials` generator dedicated config, run `npm run generate`

### This happened:

```
npm run generate

> my-catalog@0.1.0 generate
> eventcatalog generate


> @eventcatalog/core@2.13.3 generate
> node scripts/generate.js

Error loading plugin: CredentialsProviderError: Could not load credentials from any providers
    at /home/jerome/Projects/my-catalog/node_modules/@aws-sdk/credential-provider-node/dist-cjs/index.js:136:13
    at /home/jerome/Projects/my-catalog/node_modules/@smithy/property-provider/dist-cjs/index.js:97:33
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async coalesceProvider (/home/jerome/Projects/my-catalog/node_modules/@smithy/property-provider/dist-cjs/index.js:124:18)
    at async /home/jerome/Projects/my-catalog/node_modules/@smithy/property-provider/dist-cjs/index.js:142:18
    at async /home/jerome/Projects/my-catalog/node_modules/@smithy/core/dist-cjs/index.js:86:17
    at async /home/jerome/Projects/my-catalog/node_modules/@aws-sdk/middleware-logger/dist-cjs/index.js:34:22
    at async /home/jerome/Projects/my-catalog/node_modules/@eventcatalog/generator-eventbridge/dist/index.js:246:22
    at async src_default (/home/jerome/Projects/my-catalog/node_modules/@eventcatalog/generator-eventbridge/dist/index.js:307:18)
    at async generate (file:///home/jerome/Projects/my-catalog/.eventcatalog-core/scripts/generate.js:50:9) {
  tryNextLink: false
}
```

### I expected this:

generation worked

### EventCatalog Version

2.13.3

### Node.js Version

20.12.2

### Platform(s)

Linux

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by mountainmort** [comment]
Running into the same problem. Seems like this should be pulling from `options.credentials` instead of `config.credentials`?

https://github.com/event-catalog/generator-eventbridge/blob/b667a86cb5e65df2e71eff37aed0c17b7f60e444/src/index.ts#L139

**Comment by boyney123** [comment]
Thanks @mountainmort and @JSteunouSteeple , you are right @mountainmort I made the change in @eventcatalog/generator-eventbridge@1.2.3, hopefully this fixes you issue.

I tried myself, could replicate the bug and then this fixed it 🙏

**Comment by boyney123** [comment]
@JSteunouSteeple great! Let me know if you have any more questions or issues, happy to help.
